---
- name: Live CD playbook
  become: true
  vars_files:
    - ./vars.yml

  tasks:

    - name: Check that working folder is set
      ansible.builtin.fail: msg="Please set the working_folder path with no trailing hash in vars.yml"
      when: not working_folder or working_folder[-1] == "/"

    - name: Check that user is set
      ansible.builtin.fail: msg="Please set your user in vars.yml"
      when: not user

    - name: Check that group is set
      ansible.builtin.fail: msg="Please set your user group in vars.yml"
      when: not group

    - name: Install applications we need to build the environment
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: true
      with_items:
        - debootstrap
        - squashfs-tools
        - xorriso
        - isolinux
        - syslinux-efi
        - grub-pc-bin
        - grub-efi-amd64-bin
        - grub-efi-ia32-bin
        - mtools
        - dosfstools
