---
- name: Live CD playbook
  hosts: "{{ hosts }}"
  gather_facts: false
  become: true
  vars_files:
    - ./vars.yml

  tasks:

    - name: Check that working folder is set
      ansible.builtin.fail: msg="Please set the working_folder path with no trailing hash in vars.yml"
      when: not working_folder or working_folder[-1] == "/"

    - name: Check other required variables are set
      ansible.builtin.fail: msg="Please set {{ item }} in vars.yml"
      when: item|string == ''
      with_items:
        - user
        - group
        - user_password
        - root_password
        - debian_mirror

    - name: Install applications we need to build the environment
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: true
      with_items:
        - debootstrap
        - squashfs-tools
        - xorriso
        - isolinux
        - syslinux-efi
        - grub-pc-bin
        - grub-efi-amd64-bin
        - grub-efi-ia32-bin
        - mtools
        - dosfstools

    - name: Remove the working folder if it already exists
      ansible.builtin.file:
        path: "{{ working_folder }}"
        state: absent

    - name: Create the working folder where we store all the files
      ansible.builtin.file:
        path: "{{ working_folder }}"
        state: directory
        owner: "{{ user }}"
        group: "{{ group }}"
        mode: 0755

    - name: Bootstrap and configure Debian
      ansible.builtin.command: >
        /usr/sbin/debootstrap
        --arch=amd64
        --variant=minbase
        bullseye
        {{ working_folder }}/chroot
        {{ debian_mirror }}
      args:
        creates: "{{ working_folder }}/chroot"

    - name: Template Gnome Desktop Manager install script file
      ansible.builtin.template:
        src: gdm_install.j2
        dest: "{{ working_folder }}/chroot/gdm_install.sh"
        owner: "{{ user }}"
        group: "{{ group }}"
        mode: 0744

    - name: Run configuration and install custom packages
      ansible.builtin.command: /usr/sbin/chroot {{ working_folder }}/chroot ./gdm_install.sh
